In [2]:
pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\venka\appdata\local\programs\python\python314\lib\site-packages (from seaborn) (2.4.0)
Requirement already satisfied: pandas>=1.2 in c:\users\venka\appdata\local\programs\python\python314\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\venka\appdata\local\programs\python\python314\lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\venka\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\venka\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\venka\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\venka\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\venka\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\venka\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\venka\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\venka\appdata\local\programs\python\python314\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\venka\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\venka\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\venka\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns",None)

In [5]:
outfits = pd.read_csv("D:/Dare X AI/Data/outfits.csv")

outfits.head()

,outfit_id,gender,wear_type,occasion,theme,hero,hero_id,second,second_id,layer,layer_id,footwear,footwear_id,accessory_1,accessory_1_id,accessory_2,accessory_2_id,palette,items_count,total_price_inr,image_files,stylist_rationale
0,outfit W1,women,western,party,Black cocktail,Women Bodycon Midi Length Dress (Fyre Rose),ajio_703182002,NaN,NaN,NaN,NaN,Classic Women's Heels (Lavie),myntra_42540276,Sparkle Framed Clutch (Lavie),myntra_15660676,NaN,NaN,black / red,3,2313,images/ajio/703182002.jpg;images/myntra/425402...,Black midi with a gold chain waist detail; gol...
1,outfit W2,women,western,party,Wine bodycon evening,Bodycon Midi Dress (MULVARI),myntra_41733768,NaN,NaN,NaN,NaN,Open Toe Kitten Heel Sandals (Mochi),myntra_31751105,Women Embellished Clutch with Lock (Rubans),ajio_701677398,NaN,NaN,maroon / red / white,3,1977,images/myntra/41733768.jpg;images/myntra/31751...,Sleek wine square-neck bodycon; nude-tan kitte...
2,outfit W3,women,western,party,"Magenta slip, night out",Ruched Asymmetrical Midi Dress (MANGO),myntra_34682942,NaN,NaN,NaN,NaN,Women Stiletto Pumps (Shoetopia),myntra_32069236,Sling Bag with Quilted (Exotic),myntra_24130018,NaN,NaN,red / white / black,3,3870,images/myntra/34682942.jpg;images/myntra/32069...,Magenta ruched slip dress with white pointed a...
3,outfit W4,women,ethnic,festive,Dusty-blue Anarkali,Women Embellished Anarkali Kurta Suit Set (SVA...,ajio_702454568,NaN,NaN,NaN,NaN,Women Malak Brown Solid Juttis (YASSIO),nykaa_24377703,Women Stone-Studded Necklace & Earrings Set (V...,ajio_700825576,Women PU Clutches (ESBEDA),myntra_39451752,grey / brown / pink / black,4,3894,images/ajio/702454568.jpg;images/nykaa/2437770...,Dusty blue-grey anarkali with gold embroidery;...
4,outfit W5,women,ethnic,wedding,Red Banarasi saree,Women Floral Woven Banarasi Silk Saree (Stylee...,ajio_467147176,NaN,NaN,NaN,NaN,Women Fusion Embellished Juttis (DFR),ajio_703351510,Gold-Plated Jewellery Set (PANASH),myntra_7451803,Embroidered Potli Clutch (Anouk),myntra_41578752,red / cream / white,4,5066,images/ajio/467147176.jpg;images/ajio/70335151...,Classic red Banarasi silk with gold zari; gold...

In [6]:
print(outfits.shape)

outfits.info()

(25, 22)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   outfit_id          25 non-null     object
 1   gender             25 non-null     object
 2   wear_type          25 non-null     object
 3   occasion           25 non-null     object
 4   theme              25 non-null     object
 5   hero               25 non-null     object
 6   hero_id            25 non-null     object
 7   second             13 non-null     object
 8   second_id          13 non-null     object
 9   layer              4 non-null      object
 10  layer_id           4 non-null      object
 11  footwear           25 non-null     object
 12  footwear_id        25 non-null     object
 13  accessory_1        22 non-null     object
 14  accessory_1_id     22 non-null     object
 15  accessory_2        4 non-null      object
 16  accessory_2_id     4 non-null      object
 17  palette            25 non-null     object
 18  items_count        25 non-null     int64
 19  total_price_inr    25 non-null     int64
 20  image_files        25 non-null     object
 21  stylist_rationale  25 non-null     object
dtypes: int64(2), object(20)
memory usage: 4.4+ KB

In [7]:
outfits["occasion"].value_counts()

occasion
party       6
casual      5
festive     4
wedding     3
office      2
vacation    2
sports      2
winter      1
Name: count, dtype: int64

In [8]:
outfits["wear_type"].value_counts()

wear_type
western    19
ethnic      6
Name: count, dtype: int64

In [9]:
outfits["hero"].value_counts().head(20)

hero
Women Bodycon Midi Length Dress (Fyre Rose)                      1
Bodycon Midi Dress (MULVARI)                                     1
Ruched Asymmetrical Midi Dress (MANGO)                           1
Women Embellished Anarkali Kurta Suit Set (SVARAA)               1
Women Floral Woven Banarasi Silk Saree (Styleelite)              1
Women Elegance Sharara Kurta Set (Nyrika)                        1
Women Navy Blue Print Long Sleeves Formal Shirt (Van Heusen)     1
Floral Print Peplum Top (Anouk Mirage)                           1
Women Floral Print Maxi Fit & Flare Dress (LEIA)                 1
Women 2-Piece Co-Ord Set (Lulu & Sky)                            1
Zen Round Neck Tank Top for Women, 4 Way Stretchable (Hunnit)    1
Open Knit Pullover Sweater (Roadster)                            1
Formal Shirt (Chemistry)                                         1
Marquee White Sequin Printed Dress (VERO MODA)                   1
Women Embroidered Straight Kurta Suit Set (SVARAA)               1
Slim Fit Casual Shirt (Aldeno)                                   1
Men Regular Fit Linen Shirt (NEONOMAD)                           1
Men Regular Fit 2-Piece Suit Set (ARROW)                         1
Cotton Slim Fit Formal Shirt (Arrow)                             1
Men Oversized Fit Crew-Neck Sweatshirt (DNMX)                    1
Name: count, dtype: int64

In [10]:
wedding = outfits[
    outfits["occasion"]=="wedding"
]

wedding[
[
    "hero",
    "footwear",
    "accessory_1",
    "accessory_2"
]
]

,hero,footwear,accessory_1,accessory_2
4,Women Floral Woven Banarasi Silk Saree (Stylee...,Women Fusion Embellished Juttis (DFR),Gold-Plated Jewellery Set (PANASH),Embroidered Potli Clutch (Anouk)
17,Men Regular Fit 2-Piece Suit Set (ARROW),Men Formal Lace-Up Shoes with Faux Leather Upp...,Men Water-Resistant Analogue Watch-90200SL04 (...,NaN
21,Men Texture Solid Indowestern Sherwani Churida...,Men Elevator Casual Heeled Slip-on Traditional...,Men Water-Resistant Analogue Watch-90200SL04 (...,NaN

In [11]:
party = outfits[
    outfits["occasion"]=="party"
]

party[
[
    "hero",
    "footwear",
    "accessory_1"
]
]

,hero,footwear,accessory_1
0,Women Bodycon Midi Length Dress (Fyre Rose),Classic Women's Heels (Lavie),Sparkle Framed Clutch (Lavie)
1,Bodycon Midi Dress (MULVARI),Open Toe Kitten Heel Sandals (Mochi),Women Embellished Clutch with Lock (Rubans)
2,Ruched Asymmetrical Midi Dress (MANGO),Women Stiletto Pumps (Shoetopia),Sling Bag with Quilted (Exotic)
9,Women 2-Piece Co-Ord Set (Lulu & Sky),Women Slip-On Flat Sandals (JM LOOKS),Sling Bag with Quilted (Exotic)
13,Marquee White Sequin Printed Dress (VERO MODA),Open Toe Kitten Heel Sandals (Mochi),Sparkle Framed Clutch (Lavie)
24,Textured Spread Collar Shirt (Instafab Plus),Men Patterned Low-Top Loafers (U.S. Polo Assn.),Men Water-Resistant Analogue Watch-90200SL04 (...

In [12]:
outfits["footwear"].value_counts().head(20)

footwear
Women Lace-Up Fastening Sneakers (Forever Glam by Pantaloons)    3
Men Elevator Casual Heeled Slip-on Traditional Jutti (BXXY)      2
Open Toe Kitten Heel Sandals (Mochi)                             2
Women Slip-On Flat Sandals (JM LOOKS)                            2
Women Malak Brown Solid Juttis (YASSIO)                          2
Men Softride Carson Fresh Running Shoes (Puma)                   2
Men Patterned Low-Top Loafers (U.S. Polo Assn.)                  2
Classic Women's Heels (Lavie)                                    1
Women Fusion Embellished Juttis (DFR)                            1
Party Block Pumps with Buckles (CHINRAAG)                        1
Bow Detail Kitten Heel Pumps (Carlton London)                    1
Women Stiletto Pumps (Shoetopia)                                 1
Solid Black Chunky Boots (DressBerry)                            1
Men Formal Lace-Up Shoes with Faux Leather Upper (KOSHER)        1
Men Double-Strap Slip-On Sandals (SPYKAR)                        1
Men Slip-On Formal Shoes (REGAL)                                 1
Men Ankle-Length Chelsea Boots with Lace Fastening (BUCIK)       1
Name: count, dtype: int64

In [13]:
accessories = pd.concat(
[
    outfits["accessory_1"],
    outfits["accessory_2"]
]
)

accessories.value_counts().head(20)

Sling Bag with Quilted (Exotic)                                                                      4
Men Water-Resistant Analogue Watch-90200SL04 (TITAN)                                                 4
ANIME - Men Baseball Caps (BEWAKOOF)                                                                 3
Sparkle Framed Clutch (Lavie)                                                                        2
Women Stone-Studded Necklace & Earrings Set (VATSALYA)                                               2
Brown UV Protection Oval Full Rim Casual Women Sunglass - VS 2301-Gold-BRN (40) (HASHTAG EYEWEAR)    2
Shopper Shoulder Bag (MANGO)                                                                         2
Men Analogue Watch-NU1825SL16 (TITAN)                                                                2
Women Embellished Clutch with Lock (Rubans)                                                          1
Gold-Plated Jewellery Set (PANASH)                                                                   1
Drop Earrings (Zaveri Pearls)                                                                        1
Women PU Clutches (ESBEDA)                                                                           1
Embroidered Potli Clutch (Anouk)                                                                     1
Name: count, dtype: int64

In [14]:
pd.crosstab(
    outfits["occasion"],
    outfits["wear_type"]
)

wear_type  ethnic  western
occasion
casual          0        5
festive         4        0
office          0        2
party           0        6
sports          0        2
vacation        0        2
wedding         2        1
winter          0        1

In [15]:
compatibility_pairs = []

for _, row in outfits.iterrows():

    hero = row["hero"]

    if pd.notna(row["footwear"]):

        compatibility_pairs.append(
            (hero,row["footwear"])
        )

    if pd.notna(row["accessory_1"]):

        compatibility_pairs.append(
            (hero,row["accessory_1"])
        )

    if pd.notna(row["accessory_2"]):

        compatibility_pairs.append(
            (hero,row["accessory_2"])
        )

compatibility_pairs[:20]

[('Women Bodycon Midi Length Dress (Fyre Rose)',
  "Classic Women's Heels (Lavie)"),
 ('Women Bodycon Midi Length Dress (Fyre Rose)',
  'Sparkle Framed Clutch (Lavie)'),
 ('Bodycon Midi Dress (MULVARI)', 'Open Toe Kitten Heel Sandals (Mochi)'),
 ('Bodycon Midi Dress (MULVARI)',
  'Women Embellished Clutch with Lock (Rubans)'),
 ('Ruched Asymmetrical Midi Dress (MANGO)',
  'Women Stiletto Pumps (Shoetopia)'),
 ('Ruched Asymmetrical Midi Dress (MANGO)', 'Sling Bag with Quilted (Exotic)'),
 ('Women Embellished Anarkali Kurta Suit Set (SVARAA)',
  'Women Malak Brown Solid Juttis (YASSIO)'),
 ('Women Embellished Anarkali Kurta Suit Set (SVARAA)',
  'Women Stone-Studded Necklace & Earrings Set (VATSALYA)'),
 ('Women Embellished Anarkali Kurta Suit Set (SVARAA)',
  'Women PU Clutches (ESBEDA)'),
 ('Women Floral Woven Banarasi Silk Saree (Styleelite)',
  'Women Fusion Embellished Juttis (DFR)'),
 ('Women Floral Woven Banarasi Silk Saree (Styleelite)',
  'Gold-Plated Jewellery Set (PANASH)'),
 ('Women Floral Woven Banarasi Silk Saree (Styleelite)',
  'Embroidered Potli Clutch (Anouk)'),
 ('Women Elegance Sharara Kurta Set (Nyrika)',
  'Party Block Pumps with Buckles (CHINRAAG)'),
 ('Women Elegance Sharara Kurta Set (Nyrika)',
  'Drop Earrings (Zaveri Pearls)'),
 ('Women Navy Blue Print Long Sleeves Formal Shirt (Van Heusen)',
  'Bow Detail Kitten Heel Pumps (Carlton London)'),
 ('Women Navy Blue Print Long Sleeves Formal Shirt (Van Heusen)',
  'Shopper Shoulder Bag (MANGO)'),
 ('Floral Print Peplum Top (Anouk Mirage)',
  'Women Lace-Up Fastening Sneakers (Forever Glam by Pantaloons)'),
 ('Floral Print Peplum Top (Anouk Mirage)', 'Sling Bag with Quilted (Exotic)'),
 ('Floral Print Peplum Top (Anouk Mirage)',
  'Brown UV Protection Oval Full Rim Casual Women Sunglass - VS 2301-Gold-BRN (40) (HASHTAG EYEWEAR)'),
 ('Women Floral Print Maxi Fit & Flare Dress (LEIA)',
  'Women Slip-On Flat Sandals (JM LOOKS)')]

In [16]:
compatibility_df = pd.DataFrame(
    compatibility_pairs,
    columns=["hero","compatible_item"]
)

compatibility_df.head()

,hero,compatible_item
0,Women Bodycon Midi Length Dress (Fyre Rose),Classic Women's Heels (Lavie)
1,Women Bodycon Midi Length Dress (Fyre Rose),Sparkle Framed Clutch (Lavie)
2,Bodycon Midi Dress (MULVARI),Open Toe Kitten Heel Sandals (Mochi)
3,Bodycon Midi Dress (MULVARI),Women Embellished Clutch with Lock (Rubans)
4,Ruched Asymmetrical Midi Dress (MANGO),Women Stiletto Pumps (Shoetopia)

In [17]:
compatibility_dict = {}

for hero,item in compatibility_pairs:

    if hero not in compatibility_dict:
        compatibility_dict[hero] = []

    compatibility_dict[hero].append(item)

In [18]:
hero = list(compatibility_dict.keys())[0]

print(hero)

print(compatibility_dict[hero])

Women Bodycon Midi Length Dress (Fyre Rose)
["Classic Women's Heels (Lavie)", 'Sparkle Framed Clutch (Lavie)']